// Generated by CoffeeScript 1.7.1
var Client, Server, Symbiose, app, exec;

exec = require('child_process').exec;

Server = require('./server/Server');

Client = require('./client/Client');

Symbiose = (function() {
  function Symbiose() {}

  Symbiose.prototype.Run = function() {
    return exec('../nodewebkit/nw .');
  };

  Symbiose.prototype.RunServerCli = function() {
    return this.server = new Server;
  };

  Symbiose.prototype.RunClientCli = function() {
    return this.client = new Client;
  };

  return Symbiose;

})();

app = new Symbiose;

if (process.argv[2] === '-q' && process.argv[3] === '-s') {
  app.RunServerCli();
} else if (process.argv[2] === '-q' && process.argv[3] === '-c') {
  app.RunClientCli();
} else {
  app.Run();
}
