// Generated by CoffeeScript 1.7.1
this.symbiose.directive('symClient', [
  'config', function(config) {
    return {
      restrict: 'E',
      replace: true,
      templateUrl: 'views/compiled/client.html',
      link: function(scope, elem, attr) {
        scope.config = config;
        return scope.saveConfig = function() {
          return config.Write();
        };
      }
    };
  }
]);
