// Generated by CoffeeScript 1.7.1
this.symbiose.directive('symFirst', [
  function() {
    return {
      restrict: 'E',
      replace: false,
      templateUrl: 'views/compiled/first.html',
      link: function(scope, elem, attr) {
        console.log('lol');
        return scope.lol = 'coucou';
      }
    };
  }
]);
