// Generated by CoffeeScript 1.7.1
this.symbiose.directive('symFirst', [
  '$rootScope', 'config', function($rootScope, config) {
    return {
      restrict: 'E',
      replace: true,
      templateUrl: 'views/compiled/first.html',
      link: function(scope, elem, attr) {
        scope.config = config;
        scope.applyConfig = function(mode) {
          return config.Write();
        };
        return $rootScope.$on('config_reset', function(e, config) {
          return scope.$apply(function() {
            return scope.config = config;
          });
        });
      }
    };
  }
]);
