// Generated by CoffeeScript 1.7.1
var server;

server = null;

this.symbiose.directive('symServer', [
  '$rootScope', 'config', function($rootScope, config) {
    return {
      restrict: 'E',
      replace: true,
      templateUrl: 'views/compiled/server.html',
      link: function(scope, elem, attr) {
        scope.config = config;
        scope.started = false;
        $rootScope.$on('config_reset', function(e, config) {
          return scope.$apply(function() {
            return scope.config = config;
          });
        });
        scope.saveConfig = function() {
          return config.Write();
        };
        scope.startServer = function() {
          var Server;
          scope.saveConfig();
          Server = require('../server/compiled/Server');
          server = new Server;
          return scope.started = true;
        };
        return scope.stopServer = function() {
          server.Stop();
          server = null;
          return scope.started = false;
        };
      }
    };
  }
]);
