// Generated by CoffeeScript 1.7.1
var DistantScreen, DistantScreenClient,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DistantScreen = require('../common/DistantScreen');

DistantScreenClient = (function(_super) {
  __extends(DistantScreenClient, _super);

  function DistantScreenClient(infos, socket) {
    DistantScreenClient.__super__.constructor.call(this, infos, socket);
  }

  return DistantScreenClient;

})(DistantScreen);

module.exports = DistantScreenClient;
