// Generated by CoffeeScript 1.7.1

/*
0: no log
1: error log
2: warnings
3: log
 */
var Log;

Log = (function() {
  function Log(level) {
    this.level = level;
  }

  Log.prototype.Error = function() {
    if (this.level >= 1) {
      return console.error.apply(console, arguments);
    }
  };

  Log.prototype.Warning = function() {
    if (this.level >= 2) {
      return console.log.apply(console, arguments);
    }
  };

  Log.prototype.Log = function() {
    if (this.level >= 3) {
      return console.log.apply(console, arguments);
    }
  };

  Log.prototype.SetLevel = function(level) {
    this.level = level;
  };

  return Log;

})();

module.exports = new Log(3);
