// Generated by CoffeeScript 1.7.1
var ButtonPress, ButtonRelease, EventEmitter, Exposure, Log, PointerMotion, StructureNotify, X, x11,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

x11 = require('x11');

EventEmitter = require('events').EventEmitter;

Log = require('./Log');

Exposure = x11.eventMask.Exposure;

PointerMotion = x11.eventMask.PointerMotion;

ButtonPress = x11.eventMask.ButtonPress;

ButtonRelease = x11.eventMask.ButtonRelease;

StructureNotify = x11.eventMask.StructureNotify;

X = (function(_super) {
  __extends(X, _super);

  function X(done) {
    this.grabed = false;
    x11.createClient((function(_this) {
      return function(err, display) {
        if (err != null) {
          return Log.Error(err);
        }
        _this.display = display;
        _this.X = _this.display.client;
        _this.root = _this.display.screen[0].root;
        return done();
      };
    })(this));
  }

  X.prototype.InitEventTree = function(root) {
    return this.X.QueryTree(root, (function(_this) {
      return function(err, tree) {
        if (err != null) {
          return Log.Error(err);
        }
        return tree.children.forEach(function(wid) {
          return _this.X.GetWindowAttributes(wid, function(err, attrs) {
            if (err != null) {
              return Log.Error(err);
            }
            _this.X.ChangeWindowAttributes(wid, {
              eventMask: Exposure | StructureNotify
            });
            return _this.InitEventTree(wid);
          });
        });
      };
    })(this));
  };

  X.prototype.StartPointerQuery = function() {
    console.log(this.X);
    return this.pointerTimer = setInterval((function(_this) {
      return function() {
        return _this.X.QueryPointer(_this.root, function(err, fields) {
          if (err != null) {
            return Log.Error(err);
          }
          return _this.emit('mousePos', {
            x: fields.rootX,
            y: fields.rootY
          });
        });
      };
    })(this), 10);
  };

  X.prototype.StopPointerQuery = function() {
    return clearInterval(this.pointerTimer);
  };

  X.prototype.CreateBlankCursor = function() {
    var color, cursorSourceId, gc;
    if (this.cursorId == null) {
      cursorSourceId = this.X.AllocID();
      this.X.CreatePixmap(cursorSourceId, this.captureWid, 1, 1, 1);
      gc = this.X.AllocID();
      this.X.CreateGC(gc, cursorSourceId);
      this.X.CopyArea(this.root, cursorSourceId, gc, 0, 0, 0, 0, 1, 1);
      color = {
        R: 0,
        G: 0,
        B: 0
      };
      this.cursorId = this.X.AllocID();
      this.X.CreateCursor(this.cursorId, cursorSourceId, 0, color, color, 0, 0);
    }
    return this.cursorId;
  };

  X.prototype.CreateCaptureWindow = function() {
    this.captureWid = this.X.AllocID();
    this.X.CreateWindow(this.captureWid, this.root, 0, 0, this.display.screen[0].pixel_width, this.display.screen[0].pixel_height, 0, 0, 2, 0, {
      eventMask: PointerMotion | ButtonPress | ButtonRelease
    });
    this.X.ChangeWindowAttributes(this.captureWid, {
      cursor: this.CreateBlankCursor()
    });
    this.X.MapWindow(this.captureWid);
    this.X.on('event', (function(_this) {
      return function(ev) {
        if (ev.wid === _this.captureWid) {
          if (ev.name === 'MotionNotify') {
            _this.emit('mousePos', {
              x: ev.x,
              y: ev.y
            });
          }
          if (ev.name === 'ButtonPress') {
            console.log('buttondown', ev.keycode);
            _this.emit('buttonDown', ev.keycode);
          }
          if (ev.name === 'ButtonRelease') {
            console.log('buttonup', ev.keycode);
            return _this.emit('buttonUp', ev.keycode);
          }
        }
      };
    })(this));
    return this.X.on('error', function(e) {
      return Log.Error(e);
    });
  };

  X.prototype.DestroyCaptureWindow = function() {
    this.X.removeAllListeners('event');
    this.X.DestroyWindow(this.captureWid);
    return this.captureWid = null;
  };

  X.prototype.MovePointer = function(pos) {
    var target;
    target = this.root;
    if (this.grabed) {
      target = this.captureWid;
    }
    return this.X.WarpPointer(null, target, 0, 0, 0, pos.x, pos.y);
  };

  X.prototype.Grab = function() {
    this.X.GrabPointer(this.captureWid, false, {
      eventMask: PointerMotion | ButtonPress
    }, void 0, void 0, this.captureWid, function(err, data) {
      return console.log('Grab', err, data);
    });
    return this.grabed = true;
  };

  X.prototype.Ungrab = function() {
    this.X.UngrabPointer();
    return this.grabed = false;
  };

  return X;

})(EventEmitter);

module.exports = X;
