// Generated by CoffeeScript 1.7.1
var Bus, EventEmitter,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EventEmitter = require('events').EventEmitter;

Bus = (function(_super) {
  __extends(Bus, _super);

  function Bus() {}

  return Bus;

})(EventEmitter);

module.exports = new Bus;
