// Generated by CoffeeScript 1.7.1
var DistantScreen, EventEmitter, Log, Screen, Window, X, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore');

EventEmitter = require('events').EventEmitter;

X = require('./X');

Log = require('./Log');

Window = require('./Window');

Screen = require('./Screen');

DistantScreen = (function(_super) {
  __extends(DistantScreen, _super);

  function DistantScreen(infos, socket) {
    this.socket = socket;
    DistantScreen.__super__.constructor.call(this);
    this.size = {
      width: infos.width,
      height: infos.height
    };
    this.name = infos.name;
    this.placement = infos.placement;
    this.placementReverse = infos.placementReverse;
    this.pos = {
      x: 0,
      y: 0
    };
  }

  DistantScreen.prototype.MovePointer = function(pos) {
    this.pos = pos;
    this._ContentPointer();
    return this.socket.emit('mousePos', this.pos);
  };

  DistantScreen.prototype.MovePointerRelative = function(delta) {
    this.pos.x = this.pos.x + delta.x;
    this.pos.y = this.pos.y + delta.y;
    this._ContentPointer();
    this.socket.emit('mousePos', this.pos);
    return this.HasReachedEdge();
  };

  DistantScreen.prototype._ContentPointer = function() {
    if (this.pos.x < 0) {
      this.pos.x = 0;
    }
    if (this.pos.x >= this.size.width) {
      this.pos.x = this.size.width;
    }
    if (this.pos.y < 0) {
      this.pos.y = 0;
    }
    if (this.pos.y >= this.size.height) {
      return this.pos.y = this.size.height;
    }
  };

  DistantScreen.prototype.HasReachedEdge = function() {
    var edge;
    edge = DistantScreen.__super__.HasReachedEdge.call(this, this.pos);
    if (edge === this.placementReverse) {
      return this.emit('switch');
    }
  };

  DistantScreen.prototype.AddWindow = function(win) {
    if (this.HasWindow(win)) {
      return;
    }
    DistantScreen.__super__.AddWindow.call(this, win);
    X.composite.RedirectSubwindows(win.wid, X.composite.Redirect.Automatic, (function(_this) {
      return function(err) {
        if (err != null) {
          return Log.Error('Composite: RedirectWindow', err);
        }
      };
    })(this));
    win.GetOffPixmap();
    win.ActivateDamage(this.socket);
    win.SendTo(this.socket);
    return win.Hide();
  };

  DistantScreen.prototype.DelWindow = function(win) {
    win = this.GetWindow(win);
    win.DesactivateDamage();
    X.composite.RedirectSubwindows(win.wid, (function(_this) {
      return function(err) {
        if (err != null) {
          return Log.Error('Composite: UnredirectWindows', err);
        }
      };
    })(this));
    win.Show();
    DistantScreen.__super__.DelWindow.call(this, win);
    return win;
  };

  return DistantScreen;

})(Screen);

module.exports = DistantScreen;
