// Generated by CoffeeScript 1.7.1
var Log, MouseWriter, exec;

exec = require('child_process').exec;

Log = require('./Log');

MouseWriter = (function() {
  function MouseWriter() {}

  MouseWriter.prototype._Xte = function(order, args) {
    return exec("xte -x :0.0 '" + order + " " + args + "'");
  };

  MouseWriter.prototype.MoveTo = function(pos) {
    return this._Xte('mousemove', pos.x + ' ' + pos.y);
  };

  MouseWriter.prototype.MoveRelativeTo = function(pos) {
    return this._Xte('mousermove', pos.xDelta + ' ' + (-pos.yDelta));
  };

  MouseWriter.prototype.ButtonDown = function(button) {
    return this._Xte('mousedown', button);
  };

  MouseWriter.prototype.ButtonUp = function(button) {
    return this._Xte('mouseup', button);
  };

  MouseWriter.prototype.KeyDown = function() {};

  return MouseWriter;

})();

module.exports = MouseWriter;
