// Generated by CoffeeScript 1.7.1
var EventEmitter, Log, Window, X, nextId, validAttrs, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore');

EventEmitter = require('events').EventEmitter;

X = require('./X');

Log = require('./Log');

validAttrs = {
  wid: 0,
  x: 0,
  y: 0,
  width: 100,
  height: 100,
  borderWidth: 1,
  depth: 0,
  type: 1,
  visuals: 0,
  attributes: {
    eventMask: X.defaultEventMask
  },
  visible: false,
  distant: false,
  hostId: 0
};

nextId = 0;

Window = (function(_super) {
  __extends(Window, _super);

  function Window(attrs) {
    var res;
    this.id = nextId++;
    this.Deserialize(attrs);
    console.log('NewWindow');
    if (!this.wid) {
      res = X.CreateWindow(this);
      this.wid = res[0];
      this._cgid = res[1];
    } else {
      this.GetWindowAttributes();
    }
    if (this.visible) {
      this.Show();
    }
    if (this.distant && attrs.image) {
      this.FillWindow(attrs.image);
      this.Show();
    }
    this.Init();
  }

  Window.prototype.Init = function() {
    var eventsHandlers;
    eventsHandlers = {
      ConfigureNotify: (function(_this) {
        return function(ev) {
          return _this.HandleConfigure(ev);
        };
      })(this),
      Expose: (function(_this) {
        return function(ev) {
          return _this.HandleExpose(ev);
        };
      })(this)
    };
    return X.on('event', (function(_this) {
      return function(ev) {
        if (ev.wid === _this.wid && !_this.distant) {
          if (eventsHandlers[ev.name] != null) {
            return eventsHandlers[ev.name](ev);
          }
        }
      };
    })(this));
  };

  Window.prototype.Deserialize = function(attrs) {
    var k, v, _results;
    for (k in attrs) {
      v = attrs[k];
      if (validAttrs[k] != null) {
        this[k] = v;
      }
    }
    _results = [];
    for (k in validAttrs) {
      v = validAttrs[k];
      if (this[k] == null) {
        _results.push(this[k] = v);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  Window.prototype.Serialize = function() {
    return {
      hostId: this.id,
      width: this.width,
      height: this.height,
      distant: true,
      visible: true
    };
  };

  Window.prototype.GetWindowAttributes = function() {
    return X.X.GetWindowAttributes(this.wid, (function(_this) {
      return function(err, attrs) {
        if (err != null) {
          return Log.Error(err);
        }
        return _this.Deserialize(attrs);
      };
    })(this));
  };

  Window.prototype.Show = function() {
    this.visible = true;
    return X.MapWindow(this.wid);
  };

  Window.prototype.Hide = function() {
    this.visible = false;
    return X.UnmapWindow(this.wid);
  };

  Window.prototype.HandleConfigure = function(ev) {
    if (ev.x !== this.x || ev.y !== this.y) {
      this.x = ev.x;
      this.y = ev.y;
      this.emit('moved');
    }
    if (ev.width !== this.width || ev.height !== this.height) {
      this.width = ev.width;
      this.height = ev.height;
      return this.emit('resized');
    }
  };

  Window.prototype.HandleExpose = function(ev) {
    return console.log('Expose !', this, ev);
  };

  Window.prototype.FillWindow = function(image) {
    return X.FillWindow(this, image);
  };

  Window.prototype.SendTo = function(socket) {
    return X.GetWindowImage(this, (function(_this) {
      return function(err, image) {
        if (err != null) {
          return Log.Error('GetWindowImage', err);
        }
        return socket.emit('window', _(_this.Serialize()).extend({
          image: image
        }));
      };
    })(this));
  };

  return Window;

})(EventEmitter);

module.exports = Window;
