// Generated by CoffeeScript 1.7.1
var Button1Motion, ButtonMotion, ButtonPress, ButtonRelease, EventEmitter, Exposure, KeyPress, KeyRelease, Log, PointerMotion, StructureNotify, SubstructureNotify, X, x11, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require('underscore');

x11 = require('x11');

EventEmitter = require('events').EventEmitter;

Log = require('./Log');

Exposure = x11.eventMask.Exposure;

PointerMotion = x11.eventMask.PointerMotion;

ButtonMotion = x11.eventMask.ButtonMotion;

Button1Motion = x11.eventMask.Button1Motion;

ButtonPress = x11.eventMask.ButtonPress;

ButtonRelease = x11.eventMask.ButtonRelease;

StructureNotify = x11.eventMask.StructureNotify;

SubstructureNotify = x11.eventMask.SubstructureNotify;

KeyPress = x11.eventMask.KeyPress;

KeyRelease = x11.eventMask.KeyRelease;

X = (function(_super) {
  __extends(X, _super);

  function X() {
    this.grabed = false;
    this.windowId = 0;
    this.windows = [];
    this.defaultEventMask = Exposure | PointerMotion | StructureNotify | SubstructureNotify;
  }

  X.prototype.Init = function(done) {
    return x11.createClient((function(_this) {
      return function(err, display) {
        if (err != null) {
          return Log.Error(err);
        }
        _this.display = display;
        _this.X = _this.display.client;
        _this.screen = _this.display.screen[0];
        _this.root = _this.screen.root;
        _this.InitEventTree(_this.root);
        _this.X.on('event', function(ev) {
          _this.emit('event', ev);
          if (ev.name === 'CreateNotify') {
            return _this.InitEventTree(ev.parent);
          }
        });
        _this.X.on('error', function(e) {
          return Log.Error('Main error: ', e);
        });
        _this.X.require('composite', function(err, comp) {
          if (err != null) {
            return console.error(err);
          }
          return _this.composite = comp;
        });
        _this.X.require('damage', function(err, damage) {
          if (err != null) {
            return console.error(err);
          }
          return _this.damage = damage;
        });
        _this.X.require('xtest', function(err, xTest) {
          if (err != null) {
            return console.error(err);
          }
          return _this.xTest = xTest;
        });
        return done();
      };
    })(this));
  };

  X.prototype.InitEventTree = function(root) {
    return this.X.QueryTree(root, (function(_this) {
      return function(err, tree) {
        if (err != null) {
          return Log.Error(err);
        }
        return tree.children.forEach(function(wid) {
          _this.X.ChangeWindowAttributes(wid, {
            eventMask: _this.defaultEventMask
          }, function(err) {
            return console.error('Error InitEventTree: ', wid, err);
          });
          return _this.InitEventTree(wid);
        });
      };
    })(this));
  };

  X.prototype.CreateBlankCursor = function() {
    var color, cursorSourceId, gc;
    if (this.cursorId == null) {
      cursorSourceId = this.X.AllocID();
      this.X.CreatePixmap(cursorSourceId, this.captureWid, 1, 1, 1);
      gc = this.X.AllocID();
      this.X.CreateGC(gc, cursorSourceId);
      this.X.PutImage(1, cursorSourceId, gc, 1, 1, 0, 0, 0, 1, 0);
      color = {
        R: 0,
        G: 0,
        B: 0
      };
      this.cursorId = this.X.AllocID();
      this.X.CreateCursor(this.cursorId, cursorSourceId, 0, color, color, 0, 0);
    }
    return this.cursorId;
  };

  X.prototype.CreateWindow = function(win) {
    var gc, wid;
    wid = this.X.AllocID();
    console.log('CreateWindow', win);
    this.X.CreateWindow(wid, this.root, win.x, win.y, win.width, win.height, win.borderWidth, win.depth, win.type, win.visuals, win.attributes, function(err) {
      return Log.Error('CreateWindow', err);
    });
    gc = this.X.AllocID();
    this.X.CreateGC(gc, wid, (function(_this) {
      return function(err) {
        return Log.Error('CreateGC', err);
      };
    })(this));
    return [wid, gc];
  };

  X.prototype.MapWindow = function(wid) {
    return this.X.MapWindow(wid, (function(_this) {
      return function(err) {
        return Log.Error('Map', err);
      };
    })(this));
  };

  X.prototype.UnmapWindow = function(wid) {
    return this.X.UnmapWindow(wid);
  };

  X.prototype.CreateCaptureWindow = function() {
    this.captureWid = this.X.AllocID();
    this.X.CreateWindow(this.captureWid, this.root, 0, 0, this.display.screen[0].pixel_width, this.display.screen[0].pixel_height, 0, 0, 2, 0, {
      eventMask: PointerMotion | ButtonPress | ButtonRelease | KeyPress | KeyRelease
    }, (function(_this) {
      return function(err) {
        if (err != null) {
          return Log.Error('CaptureWin', err);
        }
      };
    })(this));
    this.X.ChangeWindowAttributes(this.captureWid, {
      cursor: this.CreateBlankCursor()
    });
    this.X.MapWindow(this.captureWid);
    return this.captureWid;
  };

  X.prototype.DestroyCaptureWindow = function() {
    this.X.DestroyWindow(this.captureWid);
    return this.captureWid = null;
  };

  X.prototype.MovePointer = function(pos) {
    var target;
    target = this.root;
    return this.X.WarpPointer(0, target, 0, 0, 0, 0, pos.x, pos.y);
  };

  X.prototype.Grab = function() {
    this.X.GrabPointer(this.captureWid, false, {
      eventMask: PointerMotion | ButtonPress
    }, void 0, void 0, this.captureWid, function(err, data) {
      return console.log('Grab', err, data);
    });
    return this.grabed = true;
  };

  X.prototype.Ungrab = function() {
    this.X.UngrabPointer();
    return this.grabed = false;
  };

  X.prototype.GetWindowImage = function(win, region, done) {
    if ((done == null) && (region != null)) {
      done = region;
    }
    if (region == null) {
      region = {
        x: 0,
        y: 0,
        w: win.width,
        h: win.height
      };
    }
    return this.X.GetImage(2, win.wid, region.x, region.y, region.w, region.h, 0xffffffff, done);
  };

  X.prototype.FillWindow = function(win, image) {
    return this.X.PutImage(2, win.wid, win._cgid, image.region.w, image.region.h, image.region.x, image.region.y, 0, 24, image.image.data, function(err, lol) {
      return console.log('PutImage', err);
    });
  };

  X.prototype.KeyDown = function(k) {
    return this.xTest.FakeInput(this.xTest.KeyPress, k, 0, 0, 0, 0);
  };

  X.prototype.KeyUp = function(k) {
    return this.xTest.FakeInput(this.xTest.KeyRelease, k, 0, 0, 0, 0);
  };

  X.prototype.ButtonDown = function(b) {
    console.log('ButtonDown', b);
    return this.xTest.FakeInput(this.xTest.ButtonPress, b, 0, 0, 0, 0);
  };

  X.prototype.ButtonUp = function(b) {
    console.log('ButtonUp', b);
    return this.xTest.FakeInput(this.xTest.ButtonRelease, b, 0, 0, 0, 0);
  };

  return X;

})(EventEmitter);

module.exports = new X;
