// Generated by CoffeeScript 1.7.1
var appendViews, async, compileViews, fs, getViews, jade;

fs = require('fs');

jade = require('jade');

async = require('async');

getViews = function(done) {
  return fs.readdir('./views', function(err, filenames) {
    var appendPath;
    if (err != null) {
      return done(err);
    }
    appendPath = function(filename, done) {
      return done(null, {
        path: './views/' + filename,
        name: filename
      });
    };
    return async.map(filenames, appendPath, done);
  });
};

compileViews = function(files, done) {
  var jadeComp;
  jadeComp = function(file, done) {
    var fn;
    fn = jade.compileFile(file.path);
    return done(null, {
      content: fn(),
      name: file.name.split('.')[0] + '-tpl'
    });
  };
  return async.map(files, jadeComp, done);
};

appendViews = function(files, done) {
  return $(document).ready(function() {
    var appendFile;
    appendFile = function(file, done) {
      var template;
      template = '<script type="text/ng-template" id="' + file.name + '">' + file.content + '</script>';
      return $('#content').append(template);
    };
    async.each(files, appendFile);
    return done();
  });
};

getViews(function(err, files) {
  if (err != null) {
    return console.error(err);
  }
  return compileViews(files, function(err, compFiles) {
    if (err != null) {
      return console.error(err);
    }
    return appendViews(compFiles, function(err) {
      if (err != null) {
        return console.error(err);
      }
    });
  });
});
