// Generated by CoffeeScript 1.7.1
var DistantScreen, DistantScreenServer, mouse,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

mouse = require('../common/Mouse');

DistantScreen = require('../common/DistantScreen');

DistantScreenServer = (function(_super) {
  __extends(DistantScreenServer, _super);

  function DistantScreenServer(infos, socket) {
    DistantScreenServer.__super__.constructor.call(this, infos, socket);
    this.socket.emit('clientPosition', this.placement);
  }

  return DistantScreenServer;

})(DistantScreen);

module.exports = DistantScreenServer;
