// Generated by CoffeeScript 1.7.1
var Config, Server, VirtualScreen, bus, config, exports;

bus = require('../../common/compiled/Bus');

VirtualScreen = require('./VirtualScreen');

Config = require('../../gui/js/compiled/util/config');

config = new Config;

Server = (function() {
  function Server() {
    var io;
    io = require('socket.io')(config.port);
    this.socket = null;
    this.virtScreen = new VirtualScreen;
    io.sockets.on('connection', (function(_this) {
      return function(socket) {
        _this.socket = socket;
        _this.virtScreen.AddScreen(_this.socket);
        return bus.on('mousePos', function(pos) {
          return _this.Send('mousePos', pos);
        });
      };
    })(this));
  }

  Server.prototype.Send = function(action, message) {
    return this.socket.emit(action, message);
  };

  Server.prototype.Stop = function() {
    this.virtScreen.Destroy();
    this.socket = null;
    return this.virtScreen = null;
  };

  return Server;

})();

module.exports = exports = Server;
