// Generated by CoffeeScript 1.7.1
var Log, VirtualScreen, X, bus, _;

_ = require('underscore');

bus = require('../../common/compiled/Bus');

Log = require('../../common/compiled/Log');

X = require('../../common/compiled/X');

VirtualScreen = (function() {
  function VirtualScreen() {
    this.screens = [];
    this.cursorPos = {
      x: 0,
      y: 0
    };
    this.switchedOutput = false;
    this.X = new X((function(_this) {
      return function() {
        _this.screens[0] = {
          width: _this.X.display.screen[0].pixel_width,
          height: _this.X.display.screen[0].pixel_height
        };
        Log.Log('Host screen', _this.screens[0]);
        return _this.X.InitEventTree(_this.X.root);
      };
    })(this));
    this.X.on('mousePos', (function(_this) {
      return function(pos) {
        _this.cursorPos = pos;
        if ((!_this.switchedOutput && _this.cursorPos.y <= 0) || (_this.switchedOutput && _this.cursorPos.y >= _this.screens[1].height - 1)) {
          _this._SwitchOutput();
        }
        if (_this.switchedOutput) {
          return _this.socket.emit('mousePos', _this.cursorPos);
        }
      };
    })(this));
    this.X.on('buttonDown', (function(_this) {
      return function(i) {
        if (_this.switchedOutput) {
          return _this.socket.emit('buttonDown', i);
        }
      };
    })(this));
    this.X.on('buttonUp', (function(_this) {
      return function(i) {
        if (_this.switchedOutput) {
          return _this.socket.emit('buttonUp', i);
        }
      };
    })(this));
    this.X.on('window', (function(_this) {
      return function(win) {
        return _this.socket.emit('window', win);
      };
    })(this));
    this.X.on('switchOutput', (function(_this) {
      return function() {
        return _this._SwitchOutput();
      };
    })(this));
  }

  VirtualScreen.prototype._SwitchOutput = function() {
    console.log('Switch !', this.switchedOutput);
    this.switchedOutput = !this.switchedOutput;
    if (this.switchedOutput) {
      this.cursorPos = {
        x: this.cursorPos.x,
        y: this.screens[1].height - 2
      };
      this.X.CreateCaptureWindow();
      return this.X.MovePointer(this.cursorPos);
    } else {
      this.X.DestroyCaptureWindow();
      this.cursorPos = {
        x: this.cursorPos.x,
        y: 4
      };
      return this.X.MovePointer(this.cursorPos);
    }
  };

  VirtualScreen.prototype.AddScreen = function(socket) {
    this.socket = socket;
    console.log('AddScreen');
    this.socket.once('screenInfos', (function(_this) {
      return function(infos) {
        _this.screens.push(infos);
        return Log.Log('New screen added: ', infos);
      };
    })(this));
    return this.socket.emit('askScreenInfos');
  };

  VirtualScreen.prototype.Destroy = function() {};

  return VirtualScreen;

})();

module.exports = VirtualScreen;
