// Generated by CoffeeScript 1.7.1
var Keyboard, Log, MouseReader, MouseWriter, VirtualScreen, bus, x11;

x11 = require('x11');

bus = require('../../common/compiled/Bus');

Log = require('../../common/compiled/Log');

MouseReader = require('../../common/compiled/MouseReader');

MouseWriter = require('../../common/compiled/MouseWriter');

Keyboard = require('node-keyboard/keyboard');

console.log('keyboard', Keyboard);

VirtualScreen = (function() {
  function VirtualScreen() {
    this.screens = [];
    this.cursorPos = {
      x: 0,
      y: 0
    };
    this.switchedInput = false;
    x11.createClient((function(_this) {
      return function(err, display) {
        if (err != null) {
          return Log.Error(err);
        }
        _this.screens[0] = {
          width: display.screen[0].pixel_width,
          height: display.screen[0].pixel_height
        };
        return Log.Log('Host screen', _this.screens[0]);
      };
    })(this));
    this.mouseWrite = new MouseWriter;
    this.mouseWrite.MoveTo(this.cursorPos);
    this.mouseRead = new MouseReader;
    this.mouseRead.on('moved', (function(_this) {
      return function(infos) {
        return _this._UpdateCursor(infos);
      };
    })(this));
    this.mouseRead.on('buttonDown', (function(_this) {
      return function(infos) {
        _this._UpdateCursor(infos);
        return bus.emit('buttonDown', infos.button);
      };
    })(this));
    this.mouseRead.on('buttonUp', (function(_this) {
      return function(infos) {
        _this._UpdateCursor(infos);
        return bus.emit('buttonUp', infos.button);
      };
    })(this));
  }

  VirtualScreen.prototype._UpdateCursor = function(infos) {
    this.cursorPos.x += infos.xDelta;
    this.cursorPos.y -= infos.yDelta;
    if (this.cursorPos.y < 0 && (this.socket != null)) {
      if (!this.switchedInput) {
        this.SwitchInput();
      }
      this.mouseWrite.MoveTo({
        x: 1000,
        y: 1000
      });
      return this.socket.emit('mousePos', {
        x: this.cursorPos.x,
        y: this.cursorPos.y + this.screens[1].height
      });
    } else {
      if (this.switchedInput) {
        this.SwitchInput();
      }
      if (Math.abs(infos.xDelta) > 3 || Math.abs(infos.yDelta) > 3) {
        return this.mouseWrite.MoveTo(this.cursorPos);
      }
    }
  };

  VirtualScreen.prototype._SwitchInput = function() {
    return this.switchedInput = !this.switchedInput;
  };

  VirtualScreen.prototype.AddScreen = function(socket) {
    this.socket = socket;
    this.socket.once('screenInfos', (function(_this) {
      return function(infos) {
        _this.screens.push(infos);
        _this.socket.emit('initialCursorPos', _this.cursorPos);
        return Log.Log('New screen added: ', infos);
      };
    })(this));
    return this.socket.emit('askScreenInfos');
  };

  VirtualScreen.prototype.Destroy = function() {
    return this.mouseRead.Close();
  };

  return VirtualScreen;

})();

module.exports = VirtualScreen;
